version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; bin/dev" ]
    volumes:
      - .:/rspec-example-1
      - bundle:/usr/local/bundle
    tty: true
volumes:
  bundle:
